### ISSUE TITLE
Никогда не исполняется промис RewardedAd.waitForDismiss() в release build

### ISSUE THREAD

**Issue by bitk0der** [yandexmobile/yandex-ads-flutter-plugin#1]
Версия yandex_mobileads 1.1.0

В примере "Создание и показ RewardedAd" (Android 11-12):
```dart
final ad = await RewardedAd.create(
    adUnitId: 'demo-rewarded-yandex',
    onAdLoaded: () { 
        /* Do something */
    },
    onAdFailedToLoad: (error) { 
        /* Do something */
    },
  );
  await ad.load(adRequest: AdRequest());
  await ad.show();
  final reward = await ad.waitForDismiss();
  if (reward != null) debugPrint('got ${reward.amount} of ${reward.type}');
```

после отображения рекламы (30 секунд) и после закрытия рекламного окна - никогда не происходит возврат значения `await ad.waitForDismiss()` в release build (бесконечное ожидание). Событие onRewarded - так же не происходит по истечении 30 секунд и закрытии рекламного окна в release build.

В debug build - всё работает корректно.

**Comment by mobile-ads-github** [comment]
Добрый день!
Спасибо за обращение!
Мы уже занимаемся этой проблемой.

**Comment by mobile-ads-github** [comment]
Добрый день!
Подскажите, пожалуйста, как у вас сконфигурирован релизный билд?
Это просто добавление --release к команде flutter run, или как то иначе?
Настроена ли обфускация, если да, то каким образом?
Спасибо!

**Comment by bitk0der** [comment]
Release билд идёт по умолчанию при build apk.
Проблема возникает при `flutter build apk --obfuscate`, никакие классы в игнор не добавляются, возможно именно с этим связано то, что не прилетают события (я так понимаю они текстовые-именные внутри native библиотеки, но пока сам не смотрел).

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Проблема оказалась в том, что на экземпляр рекламы (RewardedAd) не хранится жестко ссылка. Поэтому иногда сборщик мусора успевает пройтись и почистить до завершения показа объявления. 
Рекомендуем хранить ссылку на RewardedAd после его создания и до окончания показа рекламного объявления.
Поправили в семпле применение Rewarded. 
Спасибо за подсвеченную проблему!
