### ISSUE TITLE
Нативная реклама?

### ISSUE THREAD

**Issue by rr8733380** [yandexmobile/yandex-ads-flutter-plugin#14]
Здравствуйте.

Есть ли в планах реализация нативной рекламы? Стоит ждать ее добавления?

**Comment by mobile-ads-github** [comment]
Здравствуйте. Извините за долгий ответ. Мы рассматриваем возможность добавления нативной рекламы, но в ближайшие планы она не входит.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25193951. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp12.07.2023, 12:49, "mobile-ads-github" ***@***.***>:
Здравствуйте. Извините за долгий ответ. Мы рассматриваем возможность добавления нативной рекламы, но в ближайшие планы она не входит.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25193967. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp12.07.2023, 12:49, "mobile-ads-github" ***@***.***>:
Closed #14 as completed.
