### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/ios/Pods/YandexMobileAds/YandexMobileAds.xcframework)

### ISSUE THREAD

**Issue by aschurf** [yandexmobile/yandex-ads-flutter-plugin#17]
Не могу собрать проект, а при pod install получаю сообщение:
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/ios/Pods/YandexMobileAds/YandexMobileAds.xcframework)

Посмотрел Podfile в примере с закомментированной строкой:
use_frameworks!

Но в этом случае проект просто зависает при сборке.  use_frameworks! :linkage => :static так же не помогло. 

Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-x64, locale ru-RU)
Xcode - develop for iOS and macOS (Xcode 14.3.1)

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25248809. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp13.07.2023, 21:57, "Aleksandr Ivanov" ***@***.***>:
Не могу собрать проект, а при pod install получаю сообщение:
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/ios/Pods/YandexMobileAds/YandexMobileAds.xcframework)
Посмотрел Podfile в примере с закомментированной строкой:
use_frameworks!
Но в этом случае проект просто зависает при сборке.  use_frameworks! :linkage => :static так же не помогло.
Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-x64, locale ru-RU)
Xcode - develop for iOS and macOS (Xcode 14.3.1)

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Спасибо за обращение! Мы уже занимаемся этой проблемой!
На всякий случай подскажите пожалуйста, какую версию flutter-plugin вы используете?

**Comment by aschurf** [comment]
Использую версию 1.3.0
Проблему удалось исправить через добавление строки 
s.static_framework = true
в yandex_mobileads.podspec

Вопрос неактуален

**Comment by aschurf** [comment]
> > Использую версию 1.3.0 Проблему удалось исправить через добавление строки s.static_framework = true в yandex_mobileads.podspec
> 
> > 
> 
> > Вопрос неактуален
> 
> 
> 
> @aschurf А релиз сборку выкладывал в стор? У меня тоже дебаг собирается, а релиз не уходит в эпплстор.

Да, уже в сторе.
