### ISSUE TITLE
Некорректное отображение interstitial ad на андроид девайсе с камерой под дисплеем

### ISSUE THREAD

**Issue by kabunov** [yandexmobile/yandex-ads-flutter-plugin#19]
При запуске example приложения из этого репозитория на девайсе с камерой под дисплеем (under display camera) виден сверху interstitial объявления виден контент предыдущего экрана. Воспроизводится на pixel 6 эмуляторе и физическом устройстве.

https://github.com/yandexmobile/yandex-ads-flutter-plugin/assets/10830314/210bbd46-e9bc-41fd-8986-015cef27c5e9

Это происходит только когда выбран источник Yandex. Для admob, например, верхняя часть экрана отображается корректно.

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Спасибо за обращение, постараемся исправить в следующей версии.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером TEST-308994. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number TEST-308994 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером TEST-309289. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number TEST-309289 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером TEST-309295. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number TEST-309295 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by Deliner** [comment]
mark 1

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером TEST-309299. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number TEST-309299 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by Deliner** [comment]
Mark 1

**Comment by Deliner** [comment]
Mark 2

**Comment by Deliner** [comment]
Mark 3

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером TEST-309435. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number TEST-309435 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Исправлено начиная с версии 6.3.0
