### ISSUE TITLE
ios. При релиз сборке пропадает номер версии. Не получается отправить ipa в Apple.

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-flutter-plugin#20]
Переоткрыл https://github.com/yandexmobile/yandex-ads-flutter-plugin/issues/7

Попробовал еще разок собрать с yandex_mobileads: ^1.4.0
MacOs 13.3.1 xcode 14.3.1

Вот что выдает, после сборки релиз версии:
┌─ App Settings ──────────────────────────┐
│ Version Number: Missing │
│ Build Number: 91 │
│ Display Name: ProStickers │
│ Deployment Target: 14.1 │
│ Bundle Identifier: com.kastapp.stickers │
│ │
│ You must set up the missing settings. │
│ │
│ To update the settings, please refer to │
│ https://docs.flutter.dev/deployment/ios │

Т.е. куда-то пропадает номер версии и это происходит только после того, когда я подключаю yandex_mobileads: ^1.4.0 Без нее никаких проблем нет. Все нормально сибирается только под pod 'YandexMobileAds', '5.2.1', все что выше - нет.

Вот так собираю релиз сборку flutter build ipa --release --bundle-sksl-path stickers_ios.sksl.json --local-engine-src-path /Volumes/DiscMac/mobile/flutter_engine4/engine/src --local-engine=ios_release

У меня немного модифицированный флаттер движок версии 3.10.0, но те правки точно не влияют на сборку.

Перезагрузи и переустановка xcode никак не помогает.

Это как я понимаю логи сборки
[Packaging.log](https://github.com/yandexmobile/yandex-ads-flutter-plugin/files/12463031/Packaging.log)

**Comment by mobile-ads-github** [comment]
Спасибо за обращение. Будем исследовать вашу проблему.

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2278. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2278 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Можете попробовать открыть Xcode, открыть Runner > Project > Runner > Info > Configurations и установить значение для  release > Runner в Generated. 
Если это не поможет есть решение на **https://stackoverflow.com/questions/61922857/how-to-force-flutter-to-update-my-version-and-build-number/73572386#73572386**. 
Советуем обновиться сразу до стабильной версии сдк 6.0.1 для flutter **https://yandex.ru/support2/mobile-ads/ru/dev/flutter/quick-start**

**Comment by stayf** [comment]
Попробовал сдк 6.0.1. Пробовал ваше решение и то что по ссылке. Не помогает. Видимо я окончательно застрял на 5.2.1 :)

**Comment by mobile-ads-github** [comment]
> Попробовал сдк 6.0.1. Пробовал ваше решение и то что по ссылке. Не помогает. Видимо я окончательно застрял на 5.2.1 :)

В ближайшее время выйдет версия сдк 6.1.0 для flutter, там мы устранили проблему. Если после обновления проблема сохранится, сообщите пожалуйста.

**Comment by mobile-ads-github** [comment]
Здравствуйте!
Проблема была решена в релизе [6.1.0](https://github.com/yandexmobile/yandex-ads-flutter-plugin/releases/tag/6.1.0).
