### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by 2000zua** [yandexmobile/yandex-ads-flutter-plugin#23]
* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.ironsource.sdk:mediationsdk:7.4.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/ironsource/sdk/mediationsdk/7.4.0/mediationsdk-7.4.0.pom
       - https://repo.maven.apache.org/maven2/com/ironsource/sdk/mediationsdk/7.4.0/mediationsdk-7.4.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/ironsource/sdk/mediationsdk/7.4.0/mediationsdk-7.4.0.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-ironsource:7.4.0.0
   > Could not find com.chartboost:chartboost-sdk:9.3.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/chartboost/chartboost-sdk/9.3.1/chartboost-sdk-9.3.1.pom
       - https://repo.maven.apache.org/maven2/com/chartboost/chartboost-sdk/9.3.1/chartboost-sdk-9.3.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/chartboost/chartboost-sdk/9.3.1/chartboost-sdk-9.3.1.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-chartboost:9.3.1.0
   > Could not find com.pangle.global:ads-sdk:5.3.0.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/pangle/global/ads-sdk/5.3.0.4/ads-sdk-5.3.0.4.pom
       - https://repo.maven.apache.org/maven2/com/pangle/global/ads-sdk/5.3.0.4/ads-sdk-5.3.0.4.pom
       - https://storage.googleapis.com/download.flutter.io/com/pangle/global/ads-sdk/5.3.0.4/ads-sdk-5.3.0.4.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-pangle:5.3.0.4.1
   > Could not find com.tapjoy:tapjoy-android-sdk:13.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/tapjoy/tapjoy-android-sdk/13.1.2/tapjoy-android-sdk-13.1.2.pom
       - https://repo.maven.apache.org/maven2/com/tapjoy/tapjoy-android-sdk/13.1.2/tapjoy-android-sdk-13.1.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/tapjoy/tapjoy-android-sdk/13.1.2/tapjoy-android-sdk-13.1.2.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-tapjoy:13.1.2.0
   > Could not find com.mbridge.msdk.oversea:mbnative:16.4.71.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/mbnative/16.4.71/mbnative-16.4.71.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/mbnative/16.4.71/mbnative-16.4.71.pom
       - https://storage.googleapis.com/download.flutter.io/com/mbridge/msdk/oversea/mbnative/16.4.71/mbnative-16.4.71.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-mintegral:16.4.71.1
   > Could not find com.mbridge.msdk.oversea:mbbanner:16.4.71.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/mbbanner/16.4.71/mbbanner-16.4.71.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/mbbanner/16.4.71/mbbanner-16.4.71.pom
       - https://storage.googleapis.com/download.flutter.io/com/mbridge/msdk/oversea/mbbanner/16.4.71/mbbanner-16.4.71.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-mintegral:16.4.71.1
   > Could not find com.mbridge.msdk.oversea:reward:16.4.71.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/reward/16.4.71/reward-16.4.71.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/reward/16.4.71/reward-16.4.71.pom
       - https://storage.googleapis.com/download.flutter.io/com/mbridge/msdk/oversea/reward/16.4.71/reward-16.4.71.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-mintegral:16.4.71.1
   > Could not find com.mbridge.msdk.oversea:mbbid:16.4.71.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/mbbid/16.4.71/mbbid-16.4.71.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/mbbid/16.4.71/mbbid-16.4.71.pom
       - https://storage.googleapis.com/download.flutter.io/com/mbridge/msdk/oversea/mbbid/16.4.71/mbbid-16.4.71.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-mintegral:16.4.71.1
   > Could not find com.mbridge.msdk.oversea:interstitialvideo:16.4.71.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mbridge/msdk/oversea/interstitialvideo/16.4.71/interstitialvideo-16.4.71.pom
       - https://repo.maven.apache.org/maven2/com/mbridge/msdk/oversea/interstitialvideo/16.4.71/interstitialvideo-16.4.71.pom
       - https://storage.googleapis.com/download.flutter.io/com/mbridge/msdk/oversea/interstitialvideo/16.4.71/interstitialvideo-16.4.71.pom
     Required by:
         project :app > com.yandex.ads.mediation:mobileads-mintegral:16.4.71.1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Running Gradle task 'assembleRelease'...                           27,7s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:512:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:242:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:534:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:753:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2446. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2446 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Good day! It looks like you don't complete integration with SDK. Please follow the documentation:
```
2.4 Add the following code to the build.gradle file in your app's Android module:
// IronSource
maven {
       url 'https://android-sdk.is.com/'
}

// Pangle
maven {
       url 'https://artifact.bytedance.com/repository/pangle'
}

// Tapjoy
maven {
       url "https://sdk.tapjoy.com/"
}

// Mintegral
maven {
       url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea"
}

// Chartboost
maven {
       url "https://cboost.jfrog.io/artifactory/chartboost-ads/"
}

````

https://yandex.ru/support2/mobile-ads/en/dev/flutter/quick-start-mm and let me know if the problem persists
