### ISSUE TITLE
Feature request: Web implementation

### ISSUE THREAD

**Issue by Arenukvern** [yandexmobile/yandex-ads-flutter-plugin#3]
Hello,
Thank you for the library!

Could you please advise, do you have plans to add web support in the future?

**Comment by mobile-ads-github** [comment]
Hello!
Sorry for the late reply.

We are considering the possibility of adding web support, but this is not included in the immediate plans.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269494. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 16:09, "mobile-ads-github" ***@***.***>:
Closed #3 as completed.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269495. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 16:09, "mobile-ads-github" ***@***.***>:
Hello!
Sorry for the late reply.
We are considering the possibility of adding web support, but this is not included in the immediate plans.
