### ISSUE TITLE
"onImpression" callback does not work on iOS

### ISSUE THREAD

**Issue by anna-galochkina** [yandexmobile/yandex-ads-flutter-plugin#34]
Добрый день!

В IOS не отрабатывает callback `onImpression` после того, как баннер просмотрен (сам баннер отображается и колбек на onAdLoaded тоже работает)

На Android возвращаются все данные корректно:

`I/flutter ( 4978): callback: impression: {"currency":"RUB","revenueUSD":"0.000044267","precision":"estimated","revenue":"0.003548737","requestId":"1714328680218020-1601456083863017616300256-production-app-host-vla-pcode-549","blockId":"demo-banner-yandex","adType":"banner","ad_unit_id":"demo-banner-yandex","network":{"name":"Yandex","adapter":"Yandex","ad_unit_id":"demo-banner-yandex"}}`

воспроизвожу на example отсюда https://github.com/yandexmobile/yandex-ads-flutter-plugin

Со `sticky-баннером` аналогичная ситуация
баннеры меняются со временем, отрабатывает `onAdLoaded`, но `onImpression` не вызывается

плагин yandex_mobileads: ^7.0.1
cocoapods (1.15.2)
Flutter 3.19.6
Dart 3.3.4

Можете подсказать как решить эту проблему на IOS?

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3198. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3198 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Добрый день! Поправили в 7.1.0.
