### ISSUE TITLE
Banner ad auto clicked

### ISSUE THREAD

**Issue by dogiaplinh** [yandexmobile/yandex-ads-flutter-plugin#39]
I added yandex banner to my production app, this issue occurs about 5% of the time. I reproduce this issue with sample app, I don't click any thing, banner ad shown and auto open ad link

- App package name: linh.dictionary
- Banner unit id: R-M-3695923-4
- Country: Vietnam
- Plugin version: 7.0.1

https://github.com/user-attachments/assets/627f09bf-ed35-40a0-808a-3cadfc5accde

**Comment by mobile-ads-github** [comment]
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-3477. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-3477 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment]
Thank you for reaching out. We have identified the issue with the advertisement. This problem will no longer occur.
