### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-flutter-plugin#5]
Добрый день. Не могу собрать проект под андроид на flutter.

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':yandex_mobileads' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10
```
Прошу поднять версию kotlin-gradle-plugin до 1.5.20 у вас в библиотеке.

**Comment by mrbroil1** [comment]
То же самое. Прошу разработчика обратить внимание на эту проблему.

**Comment by mobile-ads-github** [comment]
Здравствуйте. 
Обновимся в ближайшем релизе. 
Спасибо за обращение!

**Comment by mobile-ads-github** [comment]
Здравствуйте!
Приносим извинения за поздний ответ.
Проблема была исправлена в версии [1.2.0](https://github.com/yandexmobile/yandex-ads-flutter-plugin/releases/tag/1.2.0)

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269258. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 15:58, "mobile-ads-github" ***@***.***>:
Здравствуйте!
Приносим извинения за поздний ответ.
Проблема была исправлена в версии 1.2.0

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269268. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 15:58, "mobile-ads-github" ***@***.***>:
Closed #5 as completed.
