### ISSUE TITLE
MissingPluginException(No implementation found for method destroy on channel yandex_mobileads.bannerAd.0)

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-flutter-plugin#6]
```
flutter: MissingPluginException(No implementation found for method destroy on channel yandex_mobileads.bannerAd.0)
flutter: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
```

Проблема с файналайзером в миксине `_Ad`. Я дергаю метод `destroy`, но в нем файналайзер не отсоединяется и всегда вызывается. Чтобы файналайзер отсоеденился нужно прикреплять его через `_finalizer.attach(this, _channel, detach: this);` а не `_finalizer.attach(this, _channel);` как сейчас.

**Comment by mobile-ads-github** [comment]
Здравствуйте!
Спасибо за репорт. Поправим в ближайшем релизе.

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Проблема была решена в релиза [1.2.0](https://github.com/yandexmobile/yandex-ads-flutter-plugin/releases/tag/1.2.0).

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269068. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 15:52, "mobile-ads-github" ***@***.***>:
Closed #6 as completed.

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269066. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 15:52, "mobile-ads-github" ***@***.***>:
Здравствуйте!
Проблема была решена в релиза 1.2.0.

**Comment by alexlobur** [comment]
Постоянно в логах приходит эта ошибка с устройств пользователей:
```
Error:
MissingPluginException(No implementation found for method load on channel yandex_mobileads.bannerAd.3) | #0 

StackTrace:
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320)
```
