### ISSUE TITLE
Битая релиз сборка под iOS

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-flutter-plugin#7]
После добавления зависимости:
```
dependencies:
  yandex_mobileads: ^1.1.0
```
Интегрировал баннерную рекламу и рекламу с вознаграждением. На дебаг сборке все отлично. После сборки релиз версии через `flutter build ipa --release`, я попытался отправить сборку через Apple Transporter. Но не получается, пишет ошибку: `Не удалось создать временный пакет .itmsp для приложения Runner.ipa`

Кстати раньше мой ipa файл назывался как stickers.ipa, а теперь почему-то стал Runner.ipa
Пришлось полностью забирать ваш код к себе в проект и даунгрейдить зависимость YandexMobileAds.
В итоге только под `pod 'YandexMobileAds', '5.2.1'` все собралось корректно и сборка ушла в Apple.

**Comment by mobile-ads-github** [comment]
Добрый день!
Спасибо за обращение!
Мы уже занимаемся этой проблемой.

**Comment by mobile-ads-github** [comment]
Добрый день!
Подскажите, какую ОС вы используете, используется ли macOS и Xcode (и какой версии)?
Есть ли в сообщении об ошибке информация о bundle id?

Пробовали ли вы повторно загружать сборку с использованием версии 5.3.1? Иногда Apple Transporter может выдавать такую ошибку, но помогает перезагрузка приложения или компьютера, либо переустановка Xcode command line tools в macOS.

Если вы используете приложение Apple Transporter, сможете ли вы повторить процесс загрузки без использования приложения, но с помощью набора команд для командной строки с опцией -v detailed (информацию можно найти [здесь](https://help.apple.com/itc/transporteruserguide/#/apdATD1E1288-D1E1A1303-D1E1288A1126))?

**Comment by mobile-ads-github** [comment]
Если сборка всё ещё не собирается, пожалуйста, проверьте, что вы выполнили следующую замену:

### Pubspec.yaml
Замените строки в [pubspec.yaml](https://github.com/yandexmobile/yandex-ads-flutter-plugin/blob/3d9361f6aa971be6e42cb27d7f703244a05f06db/example/pubspec.yaml#L25-L26)
```
  yandex_mobileads:
    path: ../
```
на строку
```
  yandex_mobileads: ^1.1.0
```
с сохранением отступа.

После этого `flutter build ios` должен сгенерировать проект в _ios/Runner.xcworkspace_.

### Xcode
После генерации Xcode-проекта в случае возникновении ошибок в Хcode:

**Error (Xcode): Undefined symbol: _OBJC_CLASS_$_IronSource** — добавьте фреймворк _IronSource_:
- _TARGETS_: _Runner_ > _Build Phases_ > _Link Library with Libraries_ > _+_ > _IronSource.xcframework_

**Error (Xcode): Signing for "Runner" requires a development team** — поменяйте команду на свою:
- _TARGETS_: _Runner_ > _Signing & Capabilities_ > _Team_ > _ваша_команда_

**Comment by mobile-ads-github** [comment]
Добрый день!
При возникновении данной проблемы повторно переоткройте, пожалуйста, тикет.

**Comment by stayf** [comment]
Попробовал еще разок собрать с yandex_mobileads: ^1.4.0
MacOs 13.3.1 xcode 14.3.1 

Вот что выдает, после сборки релиз версии:
┌─ App Settings ──────────────────────────┐
│ Version Number: Missing                 │
│ Build Number: 91                        │
│ Display Name: ProStickers               │
│ Deployment Target: 14.1                 │
│ Bundle Identifier: com.kastapp.stickers │
│                                         │
│ You must set up the missing settings.   │
│                                         │
│ To update the settings, please refer to │
│ https://docs.flutter.dev/deployment/ios │

Т.е. куда-то пропадает номер версии и это происходит только после того, когда я подключаю yandex_mobileads: ^1.4.0 Без нее никаких проблем нет. Все нормально сибирается только под pod 'YandexMobileAds', '5.2.1', все что выше - нет.

Вот так собираю релиз сборку flutter build ipa --release --bundle-sksl-path stickers_ios.sksl.json --local-engine-src-path /Volumes/DiscMac/mobile/flutter_engine4/engine/src --local-engine=ios_release

У меня немного модифицированный флаттер движок версии 3.10.0, но те правки точно не влияют на сборку.

**Comment by stayf** [comment]
@mobile-ads-github Переоткрыть не могу. У меня такой кнопки нет.
