### ISSUE TITLE
Не убиваются экраны с полноэкранной рекламой и рекламой с вознаграждением на android

### ISSUE THREAD

**Issue by stayf** [yandexmobile/yandex-ads-flutter-plugin#9]
![Screenshot_20230314_091211_One UI Home](https://user-images.githubusercontent.com/1859216/224875692-ea99aae2-70b1-4035-bbf7-96386b4a75e8.jpg)
После отображения рекламы и ее закрытии остаются висеть запущенные активности в фоне. Прикрепил скриншот с проблемой посмотрите. Если открыть 10 реклам, то 10 активнойтей будут висеть. И похоже причина в том что для создания `RewardedAd` и `InterstitialAd` вы используете контекст приложения, а не активности. После того как я стал использовать контекст активности проблема ушла. Реализуйте интрефейс `ActivityAware` в `YandexMobileAdsPlugin` чтобы получить контекст активности.

**Comment by mobile-ads-github** [comment]
Добрый день!
Спасибо за репорт, постараемся исправить в следующей версии.

**Comment by mobile-ads-github** [comment]
Здравствуйте! 
Приносим извинения за поздний ответ.

Проблема была исправлена в версии [1.2.0](https://github.com/yandexmobile/yandex-ads-flutter-plugin/releases/tag/1.2.0)

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269533. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 16:12, "mobile-ads-github" ***@***.***>:
Здравствуйте!
Приносим извинения за поздний ответ.
Проблема была исправлена в версии 1.2.0

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25269536. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.07.2023, 16:12, "mobile-ads-github" ***@***.***>:
Closed #9 as completed.
